name: On Prs

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve-me')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3

  pre-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11

    - name: Lint
      run: nix-shell --pure --run "just lint"

    - name: Test
      run: nix-shell --pure --run "just test"
